#ifndef _HEAD_BOARD_CONFIG_H_
#define _HEAD_BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_21
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_41
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_39
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_40
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_38

#define AUDIO_CODEC_PA_PIN      GPIO_NUM_42
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_13
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_14
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

#define SERVO_I2C_SDA_PIN       GPIO_NUM_8
#define SERVO_I2C_SCL_PIN       GPIO_NUM_7
#define PCA9685_POWER_ENABLE_PIN GPIO_NUM_0
#define PCA9685_I2C_ADDRESS      0x40
#define PCA9685_PWM_FREQUENCY_HZ 50
#define PCA9685_TEST_CHANNEL     1
#define SERVO_LEFT_LIMIT_DEG     75.0f
#define SERVO_CENTER_DEG         105.0f
#define SERVO_RIGHT_LIMIT_DEG    135.0f
#define SERVO_TRACKING_DEADBAND_DEG 1.0f
#define SERVO_TRACKING_MIN_INTERVAL_MS 200
#define SERVO_TRACKING_MAX_SPEED_DEG_PER_SEC 15.0f
#define SERVO_STARTUP_CENTER_SETTLE_MS 2000

#endif  // _HEAD_BOARD_CONFIG_H_
